drop table if exists post CASCADE;
create table post
(
    id bigint generated by default as identity,
    password varchar(4),
    author varchar(12),
    title varchar(50),
    writtenDate varchar(20),
    content varchar(1000),
    primary key (id)
);